COMPILER = g++

FLAGS = 

PROCESSOR = Assembler.cpp Disassembler.cpp Processor.cpp main.cpp

EXTERNAL = ..\Stack\Stack.cpp ..\Onegin\TextSort.cpp ..\Onegin\Swapper.cpp

all:
	$(COMPILER) $(FLAGS) $(PROCESSOR) $(EXTERNAL) -o terminal.exe

